-- AlterTable
ALTER TABLE "Fichaje" ADD COLUMN     "distanciaM" INTEGER,
ADD COLUMN     "lat" DOUBLE PRECISION,
ADD COLUMN     "lng" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Local" ADD COLUMN     "lat" DOUBLE PRECISION,
ADD COLUMN     "lng" DOUBLE PRECISION,
ADD COLUMN     "radioMetros" INTEGER NOT NULL DEFAULT 150;
